"""Tests for core.inventory — shared source inventory."""

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

# core/inventory/tests/test_inventory.py -> repo root
sys.path.insert(0, str(Path(__file__).parents[3]))

from core.inventory import (
    build_inventory,
    detect_language,
    compare_inventories,
    update_coverage,
    get_coverage_stats,
    format_coverage_summary,
    extract_functions,
    extract_items,
    count_sloc,
    get_items,
    should_exclude,
    is_binary_file,
    is_generated_file,
    match_exclusion_reason,
    LANGUAGE_MAP,
    DEFAULT_EXCLUDES,
    GENERATED_MARKERS,
    CodeItem,
    FunctionInfo,
    KIND_FUNCTION,
    KIND_GLOBAL,
    KIND_MACRO,
    PythonExtractor,
    JavaScriptExtractor,
    CExtractor,
    JavaExtractor,
    GoExtractor,
    GenericExtractor,
)


# ── Language Detection ──────────────────────────────────────────────

class TestLanguageDetection:
    def test_python(self):
        assert detect_language("foo.py") == "python"

    def test_javascript(self):
        assert detect_language("bar.js") == "javascript"
        assert detect_language("bar.jsx") == "javascript"

    def test_typescript(self):
        assert detect_language("baz.ts") == "typescript"
        assert detect_language("baz.tsx") == "typescript"

    def test_c(self):
        assert detect_language("main.c") == "c"
        assert detect_language("header.h") == "c"

    def test_cpp(self):
        assert detect_language("main.cpp") == "cpp"
        assert detect_language("main.cc") == "cpp"

    def test_java(self):
        assert detect_language("App.java") == "java"

    def test_go(self):
        assert detect_language("main.go") == "go"

    def test_rust(self):
        assert detect_language("main.rs") == "rust"

    def test_unknown(self):
        assert detect_language("readme.md") is None
        assert detect_language("data.json") is None
        assert detect_language("noext") is None

    def test_case_insensitive(self):
        assert detect_language("FOO.PY") == "python"
        assert detect_language("BAR.CPP") == "cpp"


# ── Exclusions ──────────────────────────────────────────────────────

class TestExclusions:
    def test_directory_pattern(self):
        assert should_exclude("project/tests/test_foo.py", ["tests/"]) is True
        assert should_exclude("project/src/foo.py", ["tests/"]) is False

    def test_glob_pattern(self):
        assert should_exclude("test_foo.py", ["test_*"]) is True
        assert should_exclude("foo_test.py", ["*_test.*"]) is True
        assert should_exclude("foo.py", ["test_*"]) is False

    def test_vendor_excluded(self):
        assert should_exclude("vendor/lib/foo.js", DEFAULT_EXCLUDES) is True
        assert should_exclude("node_modules/pkg/index.js", DEFAULT_EXCLUDES) is True

    def test_binary_detection(self, tmp_path):
        binary = tmp_path / "test.bin"
        binary.write_bytes(b'\x00\x01\x02\x03')
        assert is_binary_file(binary) is True

        text = tmp_path / "test.txt"
        text.write_text("hello world")
        assert is_binary_file(text) is False

    def test_generated_file_detection(self):
        assert is_generated_file("# auto-generated by protoc\ncode here") is True
        assert is_generated_file("# DO NOT EDIT\ncode here") is True
        assert is_generated_file("# my cool module\ndef foo(): pass") is False

    def test_match_exclusion_reason(self):
        excluded, reason, pattern = match_exclusion_reason(
            "project/tests/test_foo.py", ["tests/"]
        )
        assert excluded is True
        assert reason == "pattern_match"
        assert pattern == "tests/"

    def test_match_exclusion_not_excluded(self):
        excluded, reason, pattern = match_exclusion_reason(
            "src/app.py", ["tests/"]
        )
        assert excluded is False
        assert reason is None


# ── Extractors ──────────────────────────────────────────────────────

class TestPythonExtractor:
    def test_simple_function(self):
        code = "def foo(x, y):\n    return x + y\n"
        funcs = PythonExtractor().extract("test.py", code)
        assert len(funcs) == 1
        assert funcs[0].name == "foo"
        assert funcs[0].line_start == 1
        assert "def foo(x, y)" in funcs[0].signature

    def test_async_function(self):
        code = "async def fetch(url):\n    pass\n"
        funcs = PythonExtractor().extract("test.py", code)
        assert len(funcs) == 1
        assert "async" in funcs[0].signature

    def test_syntax_error_falls_back(self):
        code = "def foo(:\n    pass\ndef bar():\n    pass\n"
        funcs = PythonExtractor().extract("test.py", code)
        # Regex fallback should find bar at least
        assert any(f.name == "bar" for f in funcs)

    def test_checked_by_default_empty(self):
        code = "def foo(): pass\n"
        funcs = PythonExtractor().extract("test.py", code)
        assert funcs[0].checked_by == []


class TestJavaScriptExtractor:
    def test_function_declaration(self):
        code = "function handleRequest(req, res) {\n}\n"
        funcs = JavaScriptExtractor().extract("test.js", code)
        assert len(funcs) == 1
        assert funcs[0].name == "handleRequest"

    def test_arrow_function(self):
        code = "const handler = (req, res) => {\n}\n"
        funcs = JavaScriptExtractor().extract("test.js", code)
        assert len(funcs) == 1
        assert funcs[0].name == "handler"

    def test_skips_keywords(self):
        code = "if (x) {\n}\nfunction real() {\n}\n"
        funcs = JavaScriptExtractor().extract("test.js", code)
        assert all(f.name != "if" for f in funcs)


class TestCExtractor:
    def test_ansi_style(self):
        code = "int main(int argc, char *argv[]) {\n    return 0;\n}\n"
        funcs = CExtractor().extract("test.c", code)
        assert len(funcs) == 1
        assert funcs[0].name == "main"

    def test_split_brace(self):
        code = "int foo(int x)\n{\n    return x;\n}\n"
        funcs = CExtractor().extract("test.c", code)
        assert len(funcs) == 1
        assert funcs[0].name == "foo"

    def test_skips_keywords(self):
        code = "if (x) {\n}\nint real(void) {\n}\n"
        funcs = CExtractor().extract("test.c", code)
        assert all(f.name != "if" for f in funcs)


class TestJavaExtractor:
    def test_method(self):
        code = "public class App {\n    public void handle(Request req) {\n    }\n}\n"
        funcs = JavaExtractor().extract("App.java", code)
        assert len(funcs) == 1
        assert funcs[0].name == "handle"


class TestGoExtractor:
    def test_function(self):
        code = "func main() {\n}\n"
        funcs = GoExtractor().extract("main.go", code)
        assert len(funcs) == 1
        assert funcs[0].name == "main"

    def test_method(self):
        code = "func (s *Server) Handle(w http.ResponseWriter) {\n}\n"
        funcs = GoExtractor().extract("server.go", code)
        assert len(funcs) == 1
        assert funcs[0].name == "Handle"


class TestGenericExtractor:
    def test_generic_function(self):
        code = "def foo():\n    pass\n"
        funcs = GenericExtractor().extract("test.rb", code)
        assert len(funcs) == 1
        assert funcs[0].name == "foo"


class TestExtractFunctions:
    def test_routes_to_correct_extractor(self):
        py_code = "def foo(): pass\n"
        funcs = extract_functions("test.py", "python", py_code)
        assert len(funcs) == 1
        assert funcs[0].signature is not None  # Python extractor sets signature

    def test_unknown_language_uses_generic(self):
        code = "def foo(): pass\n"
        funcs = extract_functions("test.unknown", "ruby", code)
        assert len(funcs) == 1


# ── Build Inventory ─────────────────────────────────────────────────

class TestBuildInventory:
    def test_basic_inventory(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main():\n    pass\n")
        (src / "utils.py").write_text("def helper(x):\n    return x\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))

        assert inv["total_files"] == 2
        assert inv["total_functions"] == 2
        assert (tmp_path / "out" / "checklist.json").exists()

    def test_sha256_present(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))
        assert inv["files"][0]["sha256"]
        assert len(inv["files"][0]["sha256"]) == 64  # SHA-256 hex length

    def test_checked_by_is_list(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))
        func = inv["files"][0]["items"][0]
        assert isinstance(func["checked_by"], list)
        assert func["checked_by"] == []

    def test_exclusion_recording(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        tests_dir = src / "tests"
        tests_dir.mkdir()
        (src / "app.py").write_text("def main(): pass\n")
        (tests_dir / "test_app.py").write_text("def test_main(): pass\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))

        assert inv["total_files"] == 1  # Only app.py
        assert len(inv["excluded_files"]) >= 1
        excluded_paths = [e["path"] for e in inv["excluded_files"]]
        assert any("test_app.py" in p for p in excluded_paths)

    def test_generated_file_excluded(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "real.py").write_text("def real(): pass\n")
        (src / "gen.py").write_text("# auto-generated by tool\ndef gen(): pass\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))

        assert inv["total_files"] == 1
        file_paths = [f["path"] for f in inv["files"]]
        assert "real.py" in file_paths
        excluded_reasons = [e["reason"] for e in inv["excluded_files"]]
        assert "generated_file" in excluded_reasons

    def test_multi_language(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")
        (src / "main.c").write_text("int main(void) {\n    return 0;\n}\n")
        (src / "app.js").write_text("function init() {\n}\n")

        inv = build_inventory(str(src), str(tmp_path / "out"))

        languages = {f["language"] for f in inv["files"]}
        assert "python" in languages
        assert "c" in languages
        assert "javascript" in languages

    def test_nonexistent_target_raises(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            build_inventory("/nonexistent/path", str(tmp_path / "out"))


# ── Compare Inventories ─────────────────────────────────────────────

class TestCompareInventories:
    def test_identical_returns_none(self):
        inv = {"files": [{"path": "a.py", "sha256": "abc"}]}
        assert compare_inventories(inv, inv) is None

    def test_detects_added(self):
        old = {"files": [{"path": "a.py", "sha256": "abc"}]}
        new = {"files": [
            {"path": "a.py", "sha256": "abc"},
            {"path": "b.py", "sha256": "def"},
        ]}
        diff = compare_inventories(old, new)
        assert "b.py" in diff["added"]

    def test_detects_removed(self):
        old = {"files": [
            {"path": "a.py", "sha256": "abc"},
            {"path": "b.py", "sha256": "def"},
        ]}
        new = {"files": [{"path": "a.py", "sha256": "abc"}]}
        diff = compare_inventories(old, new)
        assert "b.py" in diff["removed"]

    def test_detects_modified(self):
        old = {"files": [{"path": "a.py", "sha256": "abc"}]}
        new = {"files": [{"path": "a.py", "sha256": "xyz"}]}
        diff = compare_inventories(old, new)
        assert "a.py" in diff["modified"]


# ── Cumulative Coverage ─────────────────────────────────────────────

class TestCumulativeCoverage:
    def test_carry_forward_unchanged(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        out = tmp_path / "out"

        # First run
        inv1 = build_inventory(str(src), str(out))
        # Simulate coverage
        inv1["files"][0]["items"][0]["checked_by"] = ["validate:stage-a"]
        with open(out / "checklist.json", "w") as f:
            json.dump(inv1, f)

        # Second run (same source)
        inv2 = build_inventory(str(src), str(out))
        assert inv2["files"][0]["items"][0]["checked_by"] == ["validate:stage-a"]

    def test_reuse_when_source_modified(self, tmp_path):
        """build_inventory returns existing checklist even if source changed.

        The checklist is a snapshot — hashes record state at inventory time.
        Consumers detect staleness by comparing hashes to disk, not the builder.
        Pass force_rebuild=True to rehash and rebuild.
        """
        import hashlib
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        out = tmp_path / "out"

        inv1 = build_inventory(str(src), str(out))
        original_hash = inv1["files"][0]["sha256"]
        inv1["files"][0]["items"][0]["checked_by"] = ["validate:stage-a"]
        with open(out / "checklist.json", "w") as f:
            json.dump(inv1, f)

        # Modify source — disk hash now differs from checklist hash
        (src / "app.py").write_text("def main():\n    print('changed')\n")

        # Default: reuses existing inventory (snapshot preserved)
        inv2 = build_inventory(str(src), str(out))
        assert inv2["files"][0]["sha256"] == original_hash
        assert inv2["files"][0]["items"][0]["checked_by"] == ["validate:stage-a"]

        # Consumer can detect staleness by hashing disk
        disk_hash = hashlib.sha256((src / "app.py").read_bytes()).hexdigest()
        assert disk_hash != original_hash

    def test_force_rebuild_rehashes(self, tmp_path):
        """force_rebuild=True rebuilds the checklist even when one exists."""
        import hashlib
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        out = tmp_path / "out"

        inv1 = build_inventory(str(src), str(out))
        original_hash = inv1["files"][0]["sha256"]

        # Modify source
        (src / "app.py").write_text("def main():\n    print('changed')\n")

        # force_rebuild picks up the change
        inv2 = build_inventory(str(src), str(out), force_rebuild=True)
        assert inv2["files"][0]["sha256"] != original_hash
        disk_hash = hashlib.sha256((src / "app.py").read_bytes()).hexdigest()
        assert inv2["files"][0]["sha256"] == disk_hash

    def test_reuse_when_file_added(self, tmp_path):
        """New files on disk don't trigger a rebuild — checklist is a snapshot.

        Consumers discover new files by comparing checklist paths to disk.
        Use force_rebuild=True to pick up new files.
        """
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        out = tmp_path / "out"

        inv1 = build_inventory(str(src), str(out))
        (src / "new.py").write_text("def new_func(): pass\n")

        # Default: reuses — new.py is not in the snapshot
        inv2 = build_inventory(str(src), str(out))
        assert len(inv2["files"]) == 1
        assert inv2["files"][0]["path"] == "app.py"

        # force_rebuild picks up new.py
        inv3 = build_inventory(str(src), str(out), force_rebuild=True)
        assert len(inv3["files"]) == 2
        paths = {f["path"] for f in inv3["files"]}
        assert "new.py" in paths


# ── Coverage Stats ──────────────────────────────────────────────────

class TestCoverageStats:
    def test_basic_stats(self):
        inv = {
            "files": [{
                "path": "app.py",
                "functions": [
                    {"name": "foo", "checked_by": ["validate:stage-a"]},
                    {"name": "bar", "checked_by": []},
                    {"name": "baz", "checked_by": ["validate:stage-a", "understand:map"]},
                ],
            }]
        }
        stats = get_coverage_stats(inv)
        assert stats["total_functions"] == 3
        assert stats["checked_functions"] == 2
        assert stats["by_source"]["validate:stage-a"] == 2
        assert stats["by_source"]["understand:map"] == 1

    def test_empty_inventory(self):
        stats = get_coverage_stats({"files": []})
        assert stats["total_functions"] == 0
        assert stats["coverage_percent"] == 0

    def test_update_coverage_appends(self):
        inv = {
            "files": [{
                "path": "app.py",
                "functions": [
                    {"name": "foo", "checked_by": []},
                ],
            }]
        }
        update_coverage(inv, [{"file": "app.py", "function": "foo"}], "validate:stage-a")
        assert "validate:stage-a" in inv["files"][0]["functions"][0]["checked_by"]

    def test_update_coverage_deduplicates(self):
        inv = {
            "files": [{
                "path": "app.py",
                "functions": [
                    {"name": "foo", "checked_by": ["validate:stage-a"]},
                ],
            }]
        }
        update_coverage(inv, [{"file": "app.py", "function": "foo"}], "validate:stage-a")
        assert inv["files"][0]["functions"][0]["checked_by"].count("validate:stage-a") == 1

    def test_format_summary(self):
        inv = {
            "total_files": 10,
            "excluded_files": [{"path": "t.py", "reason": "test"}],
            "files": [{
                "path": "app.py",
                "functions": [
                    {"name": "foo", "checked_by": ["validate:stage-a"]},
                    {"name": "bar", "checked_by": []},
                ],
            }],
        }
        summary = format_coverage_summary(inv)
        assert "10 files" in summary
        assert "1 excluded" in summary
        assert "1/2" in summary


# ── CLI Script ──────────────────────────────────────────────────────

class TestCLIScript:
    def test_build_inventory_script(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")

        result = subprocess.run(
            [sys.executable, "build_inventory.py", "--repo", str(src), "--out", str(tmp_path / "out")],
            capture_output=True, text=True, timeout=30,
        )
        assert result.returncode == 0
        assert "Inventory:" in result.stdout
        assert (tmp_path / "out" / "checklist.json").exists()

    def test_nonexistent_repo_fails(self, tmp_path):
        result = subprocess.run(
            [sys.executable, "build_inventory.py", "--repo", "/nonexistent", "--out", str(tmp_path)],
            capture_output=True, text=True, timeout=30,
        )
        assert result.returncode == 1


# ── CodeItem / FunctionInfo ────────────────────────────────────────

class TestCodeItem:
    def test_code_item_to_dict(self):
        item = CodeItem(name="MAX_SIZE", kind=KIND_GLOBAL, line_start=5, line_end=5)
        d = item.to_dict()
        assert d["name"] == "MAX_SIZE"
        assert d["kind"] == "global"
        assert d["line_start"] == 5

    def test_code_item_from_dict_global(self):
        d = {"name": "MAX_SIZE", "kind": "global", "line_start": 5}
        item = CodeItem.from_dict(d)
        assert isinstance(item, CodeItem)
        assert not isinstance(item, FunctionInfo)
        assert item.kind == "global"

    def test_code_item_from_dict_function(self):
        d = {"name": "main", "kind": "function", "line_start": 1, "signature": "main()"}
        item = CodeItem.from_dict(d)
        assert isinstance(item, FunctionInfo)
        assert item.kind == "function"
        assert item.signature == "main()"

    def test_code_item_from_dict_old_format(self):
        """Old format (no kind field) deserialises as FunctionInfo."""
        d = {"name": "old_func", "line_start": 10, "signature": "old_func()"}
        item = CodeItem.from_dict(d)
        assert isinstance(item, FunctionInfo)
        assert item.kind == "function"

    def test_function_info_inherits_code_item(self):
        fi = FunctionInfo(name="test", line_start=1, signature="test()")
        assert isinstance(fi, CodeItem)
        assert fi.kind == "function"

    def test_function_info_to_dict_includes_kind(self):
        fi = FunctionInfo(name="test", line_start=1, signature="test()")
        d = fi.to_dict()
        assert d["kind"] == "function"
        assert "signature" in d


# ── get_items helper ───────────────────────────────────────────────

class TestGetItems:
    def test_reads_new_format(self):
        entry = {"items": [{"name": "foo", "kind": "function"}]}
        assert len(get_items(entry)) == 1

    def test_reads_old_format(self):
        entry = {"functions": [{"name": "foo"}]}
        assert len(get_items(entry)) == 1

    def test_new_format_preferred(self):
        entry = {
            "items": [{"name": "new"}],
            "functions": [{"name": "old"}],
        }
        assert get_items(entry)[0]["name"] == "new"

    def test_empty_entry(self):
        assert get_items({}) == []


# ── extract_items ──────────────────────────────────────────────────

class TestExtractItems:
    def test_python_functions(self):
        code = "def foo(): pass\ndef bar(): pass\n"
        items = extract_items("test.py", "python", code)
        funcs = [i for i in items if i.kind == KIND_FUNCTION]
        assert len(funcs) >= 2

    def test_python_globals(self):
        code = "MAX_SIZE = 100\ndef foo(): pass\n"
        items = extract_items("test.py", "python", code)
        globals_ = [i for i in items if i.kind == KIND_GLOBAL]
        names = [g.name for g in globals_]
        # MAX_SIZE is ALL_CAPS — should be captured (with tree-sitter)
        # May be empty without tree-sitter — that's OK
        if globals_:
            assert "MAX_SIZE" in names

    def test_c_macros(self):
        code = "#define BUF_SIZE 1024\n#define MAX(a,b) ((a)>(b)?(a):(b))\nvoid foo() {}\n"
        items = extract_items("test.c", "c", code)
        macros = [i for i in items if i.kind == KIND_MACRO]
        names = [m.name for m in macros]
        assert "BUF_SIZE" in names
        assert "MAX" in names

    def test_returns_code_items(self):
        code = "def foo(): pass\n"
        items = extract_items("test.py", "python", code)
        for item in items:
            assert isinstance(item, CodeItem)


# ── count_sloc ─────────────────────────────────────────────────────

class TestCountSloc:
    def test_simple_python(self):
        code = "# comment\n\ndef foo():\n    pass\n"
        sloc = count_sloc(code, "python")
        # 4 lines total, 1 blank, 1 comment = 2 SLOC
        assert sloc == 2

    def test_blank_only(self):
        assert count_sloc("\n\n\n", "python") == 0

    def test_all_comments_python(self):
        code = "# line 1\n# line 2\n"
        assert count_sloc(code, "python") == 0

    def test_c_block_comment(self):
        code = "/* block\n   comment */\nint x = 1;\n"
        sloc = count_sloc(code, "c")
        assert sloc >= 1  # at least the int x line

    def test_mixed(self):
        code = "import os\n\n# comment\ndef main():\n    pass\n"
        sloc = count_sloc(code, "python")
        # 5 lines, 1 blank, 1 comment = 3 SLOC
        assert sloc == 3

    def test_empty_file(self):
        assert count_sloc("", "python") == 0

    def test_inline_comment_counts_as_code(self):
        code = "int x = 1; // init\n"
        sloc = count_sloc(code, "c")
        assert sloc == 1  # code line, not a comment line


# ── Build inventory output format ─────────────────────────────────

class TestInventoryOutputFormat:
    def test_uses_items_key(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")
        inv = build_inventory(str(src), str(tmp_path / "out"))
        assert "items" in inv["files"][0]
        assert "functions" not in inv["files"][0]

    def test_has_sloc(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("# comment\ndef main(): pass\n")
        inv = build_inventory(str(src), str(tmp_path / "out"))
        assert "sloc" in inv["files"][0]
        assert inv["files"][0]["sloc"] >= 1

    def test_has_total_sloc(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")
        inv = build_inventory(str(src), str(tmp_path / "out"))
        assert "total_sloc" in inv
        assert inv["total_sloc"] >= 1

    def test_has_total_items(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")
        inv = build_inventory(str(src), str(tmp_path / "out"))
        assert "total_items" in inv
        assert inv["total_items"] >= 1

    def test_items_have_kind(self, tmp_path):
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.py").write_text("def main(): pass\n")
        inv = build_inventory(str(src), str(tmp_path / "out"))
        for item in inv["files"][0]["items"]:
            assert "kind" in item
